test

diff --git a/.github/workflows/npm-gulp.yml b/.github/workflows/npm-gulp.yml
--- a/.github/workflows/npm-gulp.yml
+++ b/.github/workflows/npm-gulp.yml
@@ -13,7 +13,7 @@ jobs:
 
     strategy:
       matrix:
-        node-version: [18.x, 20.x, 22.x]
+        node-version: [22.x]
 
     steps:
       - uses: actions/checkout@v4
@@ -27,61 +27,56 @@ jobs:
         run: npm install
 
       - name: Install dependencies (backend)
-        working-directory: backend
+        working-directory: Backend
         run: npm install
 
       - name: Install dependencies (frontend)
-        working-directory: frontend
+        working-directory: Frontend
         run: npm install
 
       - name: Build typescript code (backend)
-        working-directory: backend
+        working-directory: Backend
         run: npm run build
 
-      - name: Login
-        working-directory: backend
-        shell: bash
-        id: login
-        env:
-          USERNAME: ${{ secrets.USERNAME }}
-          PASSWORD: ${{ secrets.PASSWORD }}
+      - name: check health
+        working-directory: Backend
         run: |
-          echo "Starting backend server"
           npm run serve &
           SERVER_PID=$!
-          sleep 5
+          sleep 10
 
-          response=$(curl -s -X POST http://localhost:3000/post/login \
-          -H "Content-Type: application/json" \
-          -d "{\"username\":\"$USERNAME\", \"password\":\"$PASSWORD\"}")
-    
-          token=$(echo "$response" | jq -r '.token')
-
-          echo "::add-mask::$token"
-          echo "token=$token" >> $GITHUB_OUTPUT
-
+          response=$(curl -s -X GET https://localhost:3000/health)
+          if [ "$response" != "OK" ]; then
+            echo "Health check failed: $response"
+            exit 1
+          else
+            echo "Health check passed"
+          fi
           kill $SERVER_PID
           
-      - name: Run and test compiled server (backend)
-        working-directory: backend
-        shell: bash
-        run: |
-          echo "Starting backend server"
-          npm run serve &
-          SERVER_PID=$!
-          sleep 5
+          
 
-          echo "Checking /health endpoint with JWT auth..."
-          HTTP_STATUS=$(curl -k -s -o /dev/null -w '%{http_code}' \
-            -H "Authorization: Bearer ${{ steps.login.outputs.token }}" \
-            https://localhost:${{ secrets.API_PORT }}/health)
+      # - name: Login
+      #   working-directory: Backend
+      #   shell: bash
+      #   id: login
+      #   env:
+      #     USERNAME: ${{ secrets.USERNAME }}
+      #     PASSWORD: ${{ secrets.PASSWORD }}
+      #   run: |
+      #     echo "Starting backend server"
+      #     npm run serve &
+      #     SERVER_PID=$!
+      #     sleep 5
 
-          kill $SERVER_PID
+      #     response=$(curl -s -X POST http://localhost:3000/post/login \
+      #     -H "Content-Type: application/json" \
+      #     -d "{\"username\":\"$USERNAME\", \"password\":\"$PASSWORD\"}")
+    
+      #     token=$(echo "$response" | jq -r '.token')
 
-          if [ "$HTTP_STATUS" = "200" ]; then
-            echo "✅ Authenticated health check succeeded with 200"
-            exit 0
-          else
-            echo "❌ Authenticated health check failed, got $HTTP_STATUS"
-            exit 1
-          fi
+      #     echo "::add-mask::$token"
+      #     echo "token=$token" >> $GITHUB_OUTPUT
+
+      #     kill $SERVER_PID
+          
